name = "socious-io/socious-smart-contracts"
version = "0.0.0"
license = "N/A"
description = ""

[repository]
user = "socious-io"
project = "socious-smart-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.0.1-beta"
source = "github"
